// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vidxdmhyqltjrymxvfap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpZHhkbWh5cWx0anJ5bXh2ZmFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMTY2OTQsImV4cCI6MjA2ODg5MjY5NH0.KoVVz87AiWWLjiPSLxsBKWSjITfVQghQ8TH4DqKKr3Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});